### ISSUE TITLE
Whispering doesn't work on my machine? iMac 2019 27" with Sequoia 15.1 (24B83)

### ISSUE THREAD

**Issue by shyamalschandra** [rudrankriyam/Whispering#1]
What should I do?

<img width="1109" alt="Screenshot 2024-11-16 at 7 58 45 AM" src="https://github.com/user-attachments/assets/afd86ee6-bc81-4691-b6bc-83238df2d920">

**Comment by rudrankriyam** [comment]
Only Apple Silicon

**Comment by shyamalschandra** [comment]
You just changed it.  It's totally okay if you don't want to support Intel Mac.

**Comment by shyamalschandra** [comment]
> You just changed it.  It's totally okay if you don't want to support Intel Mac.

Do they have an emulator for M-series processor like Rosetta 1.5 for x86_64 running M-series apps?
